### ISSUE TITLE
How does this extension work?

### ISSUE THREAD

**Issue by jchatard** [mailmate/todoist.mmbundle#2]
Hi,

After enabling the extension, and selecting an email and triggering Add... or Add with summary...

What is supposed to happen?
On my side, nothing seems to be executed. No message, no todo in todoist...

Am I missing something?

Thiank you :)
Jérémy

**Comment by freron** [comment]
Todoist should show a window allowing you to edit the task before it's added.

If you open a Terminal window, does the following command then work:

    open "todoist://addtask"

**Comment by jchatard** [comment]
I just restarted my computor and now it's working.

Sorry for the annoyance :-)
